[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world = "37inJ1tG9kaoxmSZZUUAcV3t6QBW4PugWmCXR5cTMaP3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/Users/davirain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
